# Generated by Django 5.0 on 2023-12-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название товара')),
                ('description', models.CharField(max_length=250, verbose_name='Описание товара')),
                ('images', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Картинка')),
                ('category', models.CharField(max_length=150, verbose_name='Категория')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date_of_creation', models.DateField(verbose_name='Дата создания')),
                ('date_of_change', models.DateField(verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('description',),
            },
        ),
    ]
