# Generated by Django 5.0 on 2023-12-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название товара')),
                ('description', models.CharField(max_length=250, verbose_name='Описание товара')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('description',),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(verbose_name='Дата создания '),
        ),
    ]
